# Generated by Django 2.2.4 on 2019-08-09 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine_dust',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 20, 21, 514584, tzinfo=utc)),
        ),
    ]
