# Generated by Django 2.2.4 on 2019-08-21 02:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190809_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine_dust',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 2, 32, 28, 76707, tzinfo=utc)),
        ),
    ]
