# Generated by Django 2.2.4 on 2019-08-24 05:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190821_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 8, 24, 5, 59, 9, 890459, tzinfo=utc))),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='fine_dust',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 5, 59, 9, 761751, tzinfo=utc)),
        ),
    ]
